### ISSUE TITLE
【Dosent Works in 2019】

### ISSUE THREAD

**Issue by ghostorange** [arimger/Unity-Editor-Toolbox#1]
it looks dosent works in unity 2019

**Comment by arimger** [comment]
Sorry for the late response. I just tested everything in version 2019.2.13f1 and seems to work. If there are no errors try to press the "Apply" button in the settings file (**Editor Toolbox/EditorSettings.asset** path). Otherwise, I will appreciate more details about error, warnings or unexpected situations.

**Comment by ghostorange** [comment]
[ReorderableList] attribute dosent works




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "arimger"<notifications@github.com&gt;; 
发送时间: 2019年11月25日(星期一) 凌晨5:35
收件人: "arimger/Unity-Editor-Toolbox"<Unity-Editor-Toolbox@noreply.github.com&gt;; 
抄送: "心机Boy"<1406691745@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [arimger/Unity-Editor-Toolbox] 【Dosent Works in 2019】 (#1)




Sorry for the late response. I just tested everything in version 2019.2.13f1 and seems to work. If there are no errors try to press the "Apply" button in the settings file (Editor Toolbox/EditorSettings.asset path). Otherwise, I will appreciate more details about error, warnings or unexpected situations.

**Comment by arimger** [comment]
That's pretty strange. I need a little bit more details:

- a version of Unity you are using 
- piece of code or even sample project where I can reproduce this behavior
- ensure you have enabled Toolbox Drawers in EditorSettings and there is no CustomEditor associated to your component

**Comment by arimger** [comment]
Issue outdated.
