### ISSUE TITLE
ReferencePicker will require the referenceType to have at least one empty constructor.

### ISSUE THREAD

**Issue by amiop12** [arimger/Unity-Editor-Toolbox#100]
Perhaps you can change `Activator.CreateInstance(referenceType)` to `FormatterServices.GetUninitializedObject(referenceType)` to directly create an object bypassing the constructor.

**Comment by arimger** [comment]
Hi! Thanks for the suggestion, I will check it out.

**Comment by arimger** [comment]
@amiop12 Hello, I changed it a bit in https://github.com/arimger/Unity-Editor-Toolbox/pull/102.
For now, if a type has no default constructor or `ReferencePicker(ForceUninitializedInstance = true)` is used then Toolbox internally will use the uninitialized option.

**Comment by amiop12** [comment]
Thank you very much!
