### ISSUE TITLE
Show If Attribute is not workable in SerializedDictionary Value class

### ISSUE THREAD

**Issue by Oscar3939** [arimger/Unity-Editor-Toolbox#104]
![image](https://github.com/arimger/Unity-Editor-Toolbox/assets/152583486/0524bceb-3dce-4cef-9755-e20e7fcd12b3)
![image](https://github.com/arimger/Unity-Editor-Toolbox/assets/152583486/ba798aa9-d1dd-4a6d-bce4-31e1d5f88bb7)
It is not workable.

**Comment by arimger** [comment]
Hi, thanks for the issue. I will fix it.

**Comment by arimger** [comment]
Hi, fixed in: https://github.com/arimger/Unity-Editor-Toolbox/pull/105.
