### ISSUE TITLE
[Feature Request] Group Styles

### ISSUE THREAD

**Issue by LucianPavel728** [arimger/Unity-Editor-Toolbox#109]
Hello, I have a small request: would it be possible to add a style property to the Begin Group attribute?

I find myself using it a lot, but I'm not really a fan of the default "helpbox" style. It would be helpful if there were an option to utilize the box style as well, similar to the reorderable list.

**Comment by arimger** [comment]
Hello, I added a small extension to the `BeginGroup` and `BeginHorizontalGroup` attributes, I added **Style** property, by default it has **GroupStyle.Round** value but you can change it to **GroupStyle.Boxed**.

**Comment by LucianPavel728** [comment]
Thank you! That is great.
