### ISSUE TITLE
[Feature Request] NotPrefabObjectOnly

### ISSUE THREAD

**Issue by blawnode** [arimger/Unity-Editor-Toolbox#111]
Could be plentily useful, when you want to target something loaded in the scene.
Then one could Destroy it or SetActive it with less trouble about if it's a prefab or not.

**Comment by arimger** [comment]
Hi, if I understand correctly - there is already a `SceneObjectOnly` attribute that allows only Scene objects to be assigned (otherwise there is a warning). I'm open to potential improvements.

**Comment by blawnode** [comment]
Nah, not what I mean.
[SceneObjectOnly] is for a specific _asset_ type, selected from the Assets window, right?

The potential [NotPrefabObjectOnly] would not be for assets, but rather game objects located in a scene's hierarchy, and selected from the Hierarchy window.

**Comment by arimger** [comment]
Ok, got it. I think I can implement something similar.

**Comment by blawnode** [comment]
Hey, I appreciate it! Thank you so much!
And thank you for adding stuff even after so much time..!

**Comment by arimger** [comment]
Hello, I added `NotPrefabObjectOnly` attribute. Drawer checks if an object is a prefab, if so then input will be ignored. Additionally, I added the **AllowInstancedPrefabs** property, if **true** then prefabs from the Scene will be accepted. Is this the behaviour you expected?

**Comment by blawnode** [comment]
Good thinking with the AllowInstancedPrefabs property! I think this is exactly what I hoped for!
I'm sure this will be useful, and not only for me.

If I may suggest, maybe adding it to PrefabObjectOnly could be handy.

But that idea aside, I believe that this feature is pretty much done.
Think this issue should be closed?

**Comment by arimger** [comment]
There is already `PrefabObjectOnlyAttribute`, which allows only connected prefab objects. Yes, if you feel that everything is ok then close the issue, please.

**Comment by blawnode** [comment]
Ah yeah, I know there is a PrefabObjectOnlyAttribute. I meant that giving PrefabObjectOnlyAttribute the AllowInstancedPrefabs property is a neat idea.
For now I'll close, the idea is probably irrelevant for this specific issue, as you've solved it.

**Comment by arimger** [comment]
Ach, sorry, probably I was reading too fast :D I will consider adding it there, thanks.
