### ISSUE TITLE
[Feature Request] - Hide expandable arrow and remove indent for serialized classes

### ISSUE THREAD

**Issue by FredTA** [arimger/Unity-Editor-Toolbox#116]
I'm trying to create MonoBehaviours whose inspectors are composed of modular configs in the form of serialized classes. For example,     

```
public class TestVC : MonoBehaviour
{
    [SerializeField, HideLabel] GeneralInteractionConfig generalInteractionConfig;
...
```

And the config object

```
[Serializable]
    public class GeneralInteractionConfig
    {
        [BeginGroup("General Interaction Settings", Style = GroupStyle.Boxed)]
        [SerializeField] public bool AdminOnly = false;

        [SerializeField] public bool EnableControllerVibrations = true;

        [EndGroup]
        [SerializeField] public bool ShowTooltipsAndHighlight = true;
    }
```

The problem is, this appears like this

![image](https://github.com/user-attachments/assets/ce4982a5-ab1e-476e-864e-6ba36c46a928)

It would be fantastic if there was some way to remove this arrow and remove the indent, so these fields within the config just presented as if they were fields directly on the MonoBehaviour that contains it. 

I tried writing a custom property drawer...

```
[CustomPropertyDrawer(typeof(GeneralInteractionConfig))]
public class PushActivatableConfigDrawer : PropertyDrawer
{
    public override float GetPropertyHeight(SerializedProperty property, GUIContent label)
    {
        float totalHeight = 0;
        var iterator = property.Copy();
        var endProperty = iterator.GetEndProperty();
        iterator.NextVisible(true); // Move to the first child property
        while (!SerializedProperty.EqualContents(iterator, endProperty))
        {
            totalHeight += EditorGUI.GetPropertyHeight(iterator, true) + EditorGUIUtility.standardVerticalSpacing;
            iterator.NextVisible(false);
        }
        return totalHeight;
    }

    public override void OnGUI(Rect position, SerializedProperty property, GUIContent label)
    {
        var iterator = property.Copy();
        var endProperty = iterator.GetEndProperty();
        iterator.NextVisible(true); // Move to the first child property
        position.height = EditorGUIUtility.singleLineHeight;
        while (!SerializedProperty.EqualContents(iterator, endProperty))
        {
            DrawPropertyField(position, iterator);
            position.y += EditorGUI.GetPropertyHeight(iterator, true) + EditorGUIUtility.standardVerticalSpacing;
            iterator.NextVisible(false);
        }
    }

    private void DrawPropertyField(Rect position, SerializedProperty property)
    {
        if (property.propertyType == SerializedPropertyType.Generic)
        {
            var iterator = property.Copy();
            var endProperty = iterator.GetEndProperty();
            iterator.NextVisible(true); // Move to the first child property
            while (!SerializedProperty.EqualContents(iterator, endProperty))
            {
                EditorGUI.PropertyField(position, iterator, true);
                position.y += EditorGUI.GetPropertyHeight(iterator, true) + EditorGUIUtility.standardVerticalSpacing;
                iterator.NextVisible(false);
            }
        }
        else
        {
            EditorGUI.PropertyField(position, property, true);
        }
    }
}
```

This removes the arrow and the indent, but breaks all the Editor Toolbox stuff (groups, titles, conditional attributes etc etc)... maybe I'm just doing this wrong? If so please let me know! I'd would be great to get this working

Thank you!

**Comment by arimger** [comment]
Hello! Can you try to use `[IgnoreParent]` on the `generalInteractionConfig`? This should do exactly what you want.

**Comment by FredTA** [comment]
> Hello! Can you try to use `[IgnoreParent]` on the `generalInteractionConfig`? This should do exactly what you want.
> 
> To clarify why your drawer didn't work - all "Toolbox" drawers are handled by a different system than Unity's PropertyDrawer. To be precise I built custom property drawers on top of the native implementation, that's why you can still use built-in attributes & drawers in Toolbox's inspector. If you want to write your custom drawers and still support other features check this document: https://github.com/arimger/Unity-Editor-Toolbox/blob/develop/Assets/Editor%20Toolbox/HOWTO.md

You, sir, are a hero. [IgnoreParent] is exactly what I needed! Thanks for getting back to me so fast (and for maintaining such a great tool), absolute legend
