### ISSUE TITLE
0.13.0 breaks Player builds

### ISSUE THREAD

**Issue by nick-morhun** [arimger/Unity-Editor-Toolbox#117]
The error is

> Library/PackageCache/com.browar.editor-toolbox@0.13.0/Runtime/Serialization/SerializedDirectory.cs(19,43): error CS0246: The type or namespace name 'DefaultAsset' could not be found (are you missing a using directive or an assembly reference?)

**Comment by arimger** [comment]
Ech, I'm really sorry. I was sure I ran runtime tests. I will fix it right now.

**Comment by arimger** [comment]
Ok, right now, it is fixed and I added an additional step to run unit tests for the player mode during PRs. Hopefully, it won't happen anymore.
