### ISSUE TITLE
[Disable] and [ShowIf] will override each other

### ISSUE THREAD

**Issue by jinsediaoying** [arimger/Unity-Editor-Toolbox#12]
This happened when I want a field only show on some condition, and should shown as disabled

**Comment by jinsediaoying** [comment]
I think show/hide and enable/disable should be two seperate thing instead of using one enum

**Comment by arimger** [comment]
Hello, 

by design, there can be only one condition-related attribute, but I will implement Hide/ShowDisabledAttribute. I think it should satisfy your needs, what do you think?

**Comment by arimger** [comment]
Added with version 0.8.11, you can use [ShowDisabledIf] or [HideDisabledIf] to handle this use case.
