### ISSUE TITLE
[Feature Request]Able to remove the label line and indent from the serializable class

### ISSUE THREAD

**Issue by jinsediaoying** [arimger/Unity-Editor-Toolbox#13]
From:
![NXYUKRVJ~ T@1 GH~85%SBY](https://user-images.githubusercontent.com/25916527/124027976-0d332480-da26-11eb-9591-49e3caab8d06.png)
To:
![V~ETTX1KAAMECC5A0C M~ C](https://user-images.githubusercontent.com/25916527/124027987-102e1500-da26-11eb-97b3-9840ad06fb5b.png)
This will be very convenient for drawing list items and organize codes.

**Comment by arimger** [comment]
Sure, added to my TODO list.

**Comment by arimger** [comment]
For now, you can use [IgnoreParent] attribute to remove indentation and parent's label.

```    
public Quaternion q1;
[Line]
[IgnoreParent]
public Quaternion q2;
```
![par](https://user-images.githubusercontent.com/38333645/124350649-183caf00-dbf6-11eb-9858-2c48f8f169bf.PNG)
