### ISSUE TITLE
Vector3 and other unity structs should use a better draw function

### ISSUE THREAD

**Issue by jinsediaoying** [arimger/Unity-Editor-Toolbox#14]
Such as EditorGUI.Vector3Field, which looks much better.

**Comment by arimger** [comment]
Yup, already fixed it on the development branch and soon it should be formally available.

**Comment by arimger** [comment]
Fix available on the master/upm branch. Version 0.8.11.

![vec](https://user-images.githubusercontent.com/38333645/124350382-bdef1e80-dbf4-11eb-9672-7088b326402d.PNG)
