### ISSUE TITLE
Drawer BeginGroup not working

### ISSUE THREAD

**Issue by Vacui** [arimger/Unity-Editor-Toolbox#25]
I implemented the plugin in a massive 2018.4.24f1 project, whose functioning I do not understand for the most part.
Most of the drawers works fine, but the Group not, it just not affect the inspector.
I still have to test all the drawers, but in the meantime I would like to know if someone has any hint for the cause of this problem.

Thx in advance for your help and have a nice day,
Matteo

**Comment by arimger** [comment]
What do you mean? Something is wrong with drawing? If so, can you share screenshot?

Going back to buttons:
Maybe you are able to solve your problem by using ToolboxEditor class, I mean something like this:
```
[CustomEditor(typeof(UnityEngine.Object), true)]
public class MyCustomButtonsEditor : UnityEditor.Editor -> ToolboxEditor
{
   public override void DrawCustomInspector()
   {
      base.DrawCustomInspector();
      //here code usually placed in the OnInspectorGUI call
   }
}
```

**Comment by Vacui** [comment]
I have solved the problem, maybe, by changing the Editor to inherit from ToolboxEditor instead of Editor.
I'm still implementing the Plugin into the project, so I'm not sure if this is the end.

**Comment by arimger** [comment]
Sure, if you have any other problems feel free to create another issue and I will help you.
