### ISSUE TITLE
Feature request - Dynamic MinMaxSlider

### ISSUE THREAD

**Issue by Vacui** [arimger/Unity-Editor-Toolbox#27]
Is possible to add a DynamicMinMaxSlider that will accept variables to change its layout?
Like with the message of the _DynamicHelpBox_

**Comment by Vacui** [comment]
Thank you really much to provide the new attribute with such speed!
Unfortunately I didn't explain me right, my bad :(
What I was trying to ask for was a _Slider_ with a min and a max dynamic, to change a single float value, not a Vector2. An extension of the already built-in _Slider_ Attribute.

Is it possible?

**Comment by arimger** [comment]
Yeah, sure.

**Comment by arimger** [comment]
Hello, sorry for the late response but DynamicRangeAttribute is now available.
