### ISSUE TITLE
[Request] Draw checkbox before label instead of after

### ISSUE THREAD

**Issue by MSavioti** [arimger/Unity-Editor-Toolbox#3]
Is usually annoying how the checkbox is drawn and how often it hides the field label:

![image](https://user-images.githubusercontent.com/34958918/100475270-76823c00-30c1-11eb-9f85-8339dcb90439.png)

There's an expensive serializer that can draw the checkbox before the label with the attribute [ToggleLeft] (image taken from their site):

![image](https://user-images.githubusercontent.com/34958918/100475290-7da94a00-30c1-11eb-8007-a27b58c1b9e0.png)

Is possible to add this to your library?

Thanks in advance, your open source project helps a lot of people like me who live in countries where an unity asset can cost half of the average people monthly income.

**Comment by arimger** [comment]
Hello, actually there is [LeftToggle] attribute and you can use it without limitations. I completely forgot to add it in the README.md and to examples, really sorry for that.

**Comment by MSavioti** [comment]
That's very nice to know! Thanks for the great toolbox!
