### ISSUE TITLE
[EditorButtonAttribute]

### ISSUE THREAD

**Issue by ArcueidD** [arimger/Unity-Editor-Toolbox#31]
Good day.

I have a question about `EditorButtonAttribute`. Why it's `AttributeUsage` has `AttributeTargets.Field`? Using reflection, you can make `AttributeTargets` for method.

**Comment by arimger** [comment]
Hello, 

[EditorButtonAttribute] is currently limited to fields by design. In the current implementation, inspector buttons are treated as decorators. A bit more detail has been discussed [here](https://github.com/arimger/Unity-Editor-Toolbox/issues/28).

**Comment by ArcueidD** [comment]
Oh sorry, this issue is duplicate) I'll close it)
