### ISSUE TITLE
Attributes over all

### ISSUE THREAD

**Issue by ArcueidD** [arimger/Unity-Editor-Toolbox#32]
Good day. 

I found out that all attributes in Editor-Toolbox are going to build. It can be resolved with marking attributes [Conditional("UNITY_EDITOR")], so they will stripe from build fully without any issues.

**Comment by arimger** [comment]
Hello, 

thank you for this issue. I already have this in my TODO, will be done in the next update for sure.

**Comment by arimger** [comment]
Added [here](https://github.com/arimger/Unity-Editor-Toolbox/pull/34).
