### ISSUE TITLE
Cannot Build Project With Editor Toolboxes In It On v2020.3.30f1

### ISSUE THREAD

**Issue by OctavianTocan** [arimger/Unity-Editor-Toolbox#35]
It seems that one cannot build a project on this version of Unity if the package is added to the project. The exact culprit seems to be the TypeConstraint.cs class.

The exact error message is attached in the screenshot!

![Screenshot 2022-03-02 185704](https://user-images.githubusercontent.com/55554752/156420334-fc6ccff8-1775-480c-ac45-00410c4eacb8.png)

**Comment by OctavianTocan** [comment]
It seems that this happens on the default project with the source files too. Any specific fixes that I could go about doing that would solve this?

Your package is really helpful, so I'd love to keep using it, but not being able to build is quite a bummer.

**Comment by arimger** [comment]
I'm sorry for the trouble, I fixed it today morning. Just update the package and let me know if everything is fine.

**Comment by OctavianTocan** [comment]
It was absolutely no trouble!

I appreciate your prompt reply, and fixing of the issue! Thanks a lot for your efforts. The package is really cool,
keep up the super good work! :)
