### ISSUE TITLE
Important information missing in the (documentation) readme

### ISSUE THREAD

**Issue by jujaruiz** [arimger/Unity-Editor-Toolbox#38]
If you use a custom editor you have to:
inherit from"ToolboxEditor"  and use `public override void DrawCustomInspector()  {base.DrawCustomInspector();}`

Instead of: 
"Editor" and `public override void OnInspectorGUI() {DrawDefaultInspector();}`

But the only place you can see this, is indirectly in the "how to"  secction where a custom inspector example is available.

The proposed solution is to add this information in the main readme, so anyone that want  use a custom inspector can see hot to without exploring the documentation or the  code.

**Comment by arimger** [comment]
Sure, I will add it to the README.md.

**Comment by arimger** [comment]
Done in [v0.11.1](https://github.com/arimger/Unity-Editor-Toolbox/tree/v0.11.1).
