### ISSUE TITLE
[EditorButtonAttribute] Method call not work in nested class.

### ISSUE THREAD

**Issue by SirLpc** [arimger/Unity-Editor-Toolbox#44]
class RootClass : ScriptableObject
{
    public NestedClass childObj;
}

[Serializable]
class NestedClass
{
    [EditorButton(nameof(CallMyMethod))]
    public string testField;
    
    // Method here in nested class wont be called, but in the parent ScriptableObject will work.
    private void CallMyMethod()
    {
         // Will not be called, but expected!
    }
}

**Comment by arimger** [comment]
Yup, I know. Unfortunately, decorators have no idea on which properties they are displayed, that's why [DynamicHelp] and [EditorButton] won't work in nested classes. I have this on my TODO list, but thanks for the issue anyway.

**Comment by SirLpc** [comment]
> Yup, I know. Unfortunately, decorators have no idea on which properties they are displayed, that's why [DynamicHelp] and [EditorButton] won't work in nested classes. I have this on my TODO list, but thanks for the issue anyway.

OK, get it!

**Comment by arimger** [comment]
Thanks for the suggestion. Currently, there is no way to do this but I think I can implement it.

**Comment by arimger** [comment]
Implemented in https://github.com/arimger/Unity-Editor-Toolbox/pull/120.
