### ISSUE TITLE
UPM conflict with com.unity.editorcoroutines

### ISSUE THREAD

**Issue by Team-on** [arimger/Unity-Editor-Toolbox#5]
All scripts from Unity-Editor-Toolbox/Assets/Editor Toolbox/Editor/Routine/ can't be imported.
 
![image](https://user-images.githubusercontent.com/30273693/103346974-46ea9900-4a9e-11eb-8ba5-6a00b494f21e.png)

**Comment by arimger** [comment]
Sorry about that and thank you for the report. I will fix it today.

**Comment by Team-on** [comment]
I think you just copy scripts from editorcoroutines, isn't it? What about adding it as dependency?

**Comment by arimger** [comment]
Not exactly, I changed minor things but now it's completely redundant. I added Unity.EditorCoroutine package as a dependency and everything should be fine.

**Comment by Team-on** [comment]
Thank you for fix! Don't forget to close the issue
