### ISSUE TITLE
SerializedScene - scene index is set to -1 on first app launch

### ISSUE THREAD

**Issue by GMyjak** [arimger/Unity-Editor-Toolbox#54]
Project with error repro: [toolbox-repro](https://github.com/GMyjak/toolbox-repro)

Basically when you pull project and open it for the first time, scene index cache in `SerializedScene` is not updated or updated not correclty. Now between the time this cache is updated and the time you enter play mode, `OnBeforeSerialize` method is never called and indexes are not updated, so their value is set to -1. This causes error when trying to load scene with Unity `SceneManager.LoadScene`.

Now this wouldn't be a huge issue because indexes fix themselves after first play mode launch, but when you build app with some sort of CI and clear editor cache between builds, the app will be built with wrong indexes. This means it will never behave correctly.

You can also reproduce this error in any project using `SerializedScene` by deleting `Library/ArtifactDB`. 

Unity version: 2021.3.9 (+some older)
Build target: tested with Android and Windows, Mac, Linux

**Comment by arimger** [comment]
Hello Grzegorz! Thank you for the issue, detailed info, and reproduction repo, this will help a lot. I don't promise I will fix it this week, but definitely I will start the investigation.

**Comment by arimger** [comment]
Ok, should be fixed in [v0.11.9](https://github.com/arimger/Unity-Editor-Toolbox/releases/tag/v0.11.9). Please create another issue if this bug still occurs during your CI setup.
