### ISSUE TITLE
Got warnning "method not found" with [EditorButton(...)]

### ISSUE THREAD

**Issue by zzmingo** [arimger/Unity-Editor-Toolbox#61]
![](https://user-images.githubusercontent.com/24818119/201857886-d5ac1c0e-083d-4179-b37a-86ada433921e.png)

```
[Editor Toolbox] EditorButtonAttribute: GeneratePrefsId method not found.
```

Unity version: 2022.1.13f1

**Comment by zzmingo** [comment]
Some possible problematic situations:
This class is a abstract base class with generic type arg, named like `Base<T> : MonoBehaviour`
The sub component is named `SubClass : Base<bool>`

**Comment by arimger** [comment]
If a method is private you won't find it through the reflection using the child class. TBH I wanted to avoid searching for private methods in all base classes. Can you make this method protected or this is not acceptable in your codebase?
