### ISSUE TITLE
[ReferencePicker] not working on a list of interface

### ISSUE THREAD

**Issue by YouKiat** [arimger/Unity-Editor-Toolbox#66]
[ReferencePicker]
[SerializeReference]
private List<Interface> list;

![image](https://user-images.githubusercontent.com/29061125/226330600-0961a15e-e92d-4539-bf04-cbb7d8afe783.png)

**Comment by arimger** [comment]
It looks like you are using the default Unity list, it's not supporting **ReferencePickerAttribute**. You can use **ReorderableListAttribute** to fix it.

**Comment by YouKiat** [comment]
i see, thanks.
