### ISSUE TITLE
SerializedDictionary is not foldable

### ISSUE THREAD

**Issue by YouKiat** [arimger/Unity-Editor-Toolbox#69]
```cs
public SerializedDictionary<int, GameObject> dictionary;
```

Is there a way to make the dictionary foldable?

![image](https://user-images.githubusercontent.com/29061125/226977362-a87cda1a-342c-48dc-ae23-b4a1e21c11fe.png)

**Comment by arimger** [comment]
Unfortunately not. I will change it in the next update, thanks.

**Comment by arimger** [comment]
Changed in: https://github.com/arimger/Unity-Editor-Toolbox/pull/73.
