### ISSUE TITLE
The various If attributes doesn't support flags enums

### ISSUE THREAD

**Issue by Vacui** [arimger/Unity-Editor-Toolbox#7]
Due to the boolean nature of the ComparisonAttribute, I found no way to support flag and normal enums at the same time.
To enable the first I changed the enum switch case in the class ComparisonAttributeDrawer<T>, with this:
`return OnComparisonResult((propertyToCheck.intValue & (int)attribute.ValueToMatch) != 0);`

But by doing this I automatically disabled the use of the first value for normal (non flags) enums, to be used as a condition.
For example, with my change this no more works, because TestEnum.Test1 has an index of 0.
```
[EnableIf(nameof(testEnum), TestEnum.Test1)]
public bool test;
public enum TestEnum { Test1, Test2 }
public TestEnum testEnum = TestEnum.Test1;
```

I therefore ask you, is there another way to support flags enums while still allow to use normal enums as now?

Thank you for your help in advance, and also for making this amazing plugin free.

I wish you a good day.

**Comment by arimger** [comment]
Hello, sorry for the late answer!

I think the easiest way to achieve this is to check if the target enum is marked as Flag:
```
System.Attribute.IsDefined(attribute.ValueToMatch.GetType(), typeof(System.FlagsAttribute));
```
then you are able to handle this case differently for typical enum and flags.

However, I will add to the package something like this:
```
    public enum ComparisionTestMethod
    {
        Equal,
        Greater,
        GreaterEqual,
        Smaller,
        SmallerEqual,
        Mask
    }
```
it will make comparison attributes more flexible. By default, I will keep `ComparisionTestMethod.Equal` method, so in this particular case you will have to change the value to the `ComparisionTestMethod.Mask`.

**Comment by arimger** [comment]
```
    [System.Flags]
    public enum TestEnum
    {
        None = 0,
        Enum1 = 1,
        Enum2 = 2,
        Enum3 = 4
    }

    [EnumFlag]
    public TestEnum var0;
    [EnableIf(nameof(var0), TestEnum.Enum1 | TestEnum.Enum2, TestMethod = ComparisionTestMethod.Mask)]
    public bool var1;
```

Please, tell me if you are satisfied with this solution.

**Comment by Vacui** [comment]
Sorry? It took me over 3 days to answer you, I can't judge you.

Anyway, I tried your solution and are you sure it works?
I settled this testing script after updating the local files with your changes (never thought about setting up a package?), and I had strange results.

The testing script:
```
[System.Flags]
public enum TestEnum
{
    None = 0,
    Enum1 = 1,
    Enum2 = 2,
    Enum3 = 4
}

[EnumFlag(EnumStyle.Button)] public TestEnum var0;

[SerializeField, EnableIf(nameof(var0), TestEnum.None, TestMethod = ComparisionTestMethod.Equal)] private bool varN;
[SerializeField, EnableIf(nameof(var0), TestEnum.Enum1 | TestEnum.Enum2, TestMethod = ComparisionTestMethod.Mask)] private bool var1;
[SerializeField, EnableIf(nameof(var0), TestEnum.Enum2, TestMethod = ComparisionTestMethod.Mask)] private bool var2;
[SerializeField, EnableIf(nameof(var0), TestEnum.Enum3, TestMethod = ComparisionTestMethod.Equal)] private bool var3;
```

The results are (listed fields are what is enabled):
**Nothing**: VarN, Var1, Var2
**Everything**: None of them
**Enum1**: Var1
**Enum2**: Var1, Var2
**Enum3**: Var3
**Enum1 & 2**: Var1

What I found strange:
1. If I use only one value in a mask, it behave like an equal
2. If I select everything, nothing is enabled.

Is there something wrong in my example code or is it working as intended?

Thank you for your help, I will try to answer you quickly this time.

Bye

**Comment by arimger** [comment]
> I settled this testing script after updating the local files with your changes (never thought about setting up a package?), and I had strange results.

You can use Unity Package Manager to import this repository but you have to use the direct link to the UPM branch:
https://github.com/arimger/Unity-Editor-Toolbox.git#upm

Unfortunately, I made mistake but still, there is one thing - in my solution `var0` is the mask, and `valueToMatch` (2nd argument of the **EnableIfAttribute**) is the flag. So if `var0` is set to 'Everything' every EnableIf statement with `ComparisionTestMethod.Mask` will be true. Is this satisfying you or would like to reverse it?

**Comment by phields** [comment]
> > I settled this testing script after updating the local files with your changes (never thought about setting up a package?), and I had strange results.
> 
> You can use Unity Package Manager to import this repository but you have to use the direct link to the UPM branch:
> https://github.com/arimger/Unity-Editor-Toolbox.git#upm
> 
> Unfortunately, I made mistake but still, there is one thing - in my solution `var0` is the mask, and `valueToMatch` (2nd argument of the **EnableIfAttribute**) is the flag. So if `var0` is set to 'Everything' every EnableIf statement with `ComparisionTestMethod.Mask` will be true. Is this satisfying you or would like to reverse it?

I'm having the same issue, I think the return result of this method should be similar to HasFlag

**Comment by phields** [comment]
I modified CheckEnum as an ugly fix for ref
`            internal static bool CheckEnum(SerializedProperty propertyToCheck, object valueToMatch, ComparisionTestMethod testMethod)
            {
                return (propertyToCheck.intValue& (int)valueToMatch)!=0;
            }`

**Comment by arimger** [comment]
Since it was a request and the feature is already added I will close it. If anyone has encountered issues using mask comparison please create a new Issue.
