### ISSUE TITLE
SceneSerializationUtility RefreshCache Error

### ISSUE THREAD

**Issue by Zenodeon** [arimger/Unity-Editor-Toolbox#74]
SceneSerializationUtility 's ```RefreshCache()``` gives out an error when it is Refreshing Cache on a scene that is added to the build settings but it no longer exists.

Reproduce Method
- Add Dummy Scene
- Add it to the Build Settings
- Delete the Dummy Scene
- Restart the Editor

You will see an error that is a bit hard to trace back.

**Comment by arimger** [comment]
Got it, thanks.
