### ISSUE TITLE
Is it possible to list all interface type ?

### ISSUE THREAD

**Issue by YouKiat** [arimger/Unity-Editor-Toolbox#76]
```cs
		[field: TypeConstraint(null,
			AllowAbstract = true,
			AllowObsolete = true,
			AddTextSearchField = true,
			OrderTypes = true,
			TypeGrouping = TypeGrouping.ByFlatName,
			TypeSettings = TypeSettings.Interface)]
		private SerializedType InterfaceType { get; set; } = new();
```			
I tried the code above, but it didn't work.

**Comment by arimger** [comment]
Unfortunately not, you have to specify the base class. SerializedType underneath is using the [TypeCache](https://docs.unity3d.com/ScriptReference/TypeCache.html) class and as far as I know, there is no option to get all interfaces. Previously I was using a custom solution that scans all assemblies but for Editor Tools is highly advised to use the **TypeCache** to share the same API for retrieving types.

**Comment by YouKiat** [comment]
ok, noted, thanks.
