### ISSUE TITLE
Error while importing with UPM

### ISSUE THREAD

**Issue by grevius5** [arimger/Unity-Editor-Toolbox#8]
I was following the instrucyion to add the package with upm but when i try to add the repo i have this error:
`[Package Manager Window] Cannot perform upm operation: Unable to add package [https://github.com/arimger/Unity-Editor-Toolbox.git#upm]:
  Could not clone [https://github.com/arimger/Unity-Editor-Toolbox.git]. Revision [upm] could not be found. [NotFound].
UnityEditor.EditorApplication:Internal_CallUpdateFunctions ()`

**Comment by arimger** [comment]
Strange, the UPM branch has just disappeared but now everything should be ok. Thank you for the report.
