### ISSUE TITLE
[Feature Request] Progress bars interactability

### ISSUE THREAD

**Issue by zRevenger** [arimger/Unity-Editor-Toolbox#88]
Hi, I was wondering if it could be possible to make progress bars interactable to edit their value.
It would be useful to have it both draggable and the value editable.

**Comment by arimger** [comment]
Hi, sure, I will add it to my TODO list.

**Comment by arimger** [comment]
Implemented in: https://github.com/arimger/Unity-Editor-Toolbox/pull/93.
