### ISSUE TITLE
“OnValueChanged” and "OnAdded"

### ISSUE THREAD

**Issue by phields** [arimger/Unity-Editor-Toolbox#9]
If I want to listen for field changes how should I do it? Is it possible to add a method like OnValueChanged?
And, what should I do if I want to custom initialize a ReorderableList?

**Comment by arimger** [comment]
There is no such thing as OnValueChangedAttribute but I will consider adding it. 

What do you mean by "custom initialize"? Can you describe it?

**Comment by phields** [comment]
> There is no such thing as OnValueChangedAttribute but I will consider adding it.
> 
> What do you mean by "custom initialize"? Can you describe it?

Currently, when I click Add in the ReorderableList, the newly added element copies the value of the previous element in the ReorderableList, I want the newly added element to have a custom initial value, like Null or something, so I need an interface like OnValueChanged or OnAdded.

**Comment by arimger** [comment]
Sure, I will add it to my TODO list.

**Comment by arimger** [comment]
Ok, so:

- you can use `OnValueChangedAttribute` but unfortunately, it's based on PropertyAttribute and cannot be combined with any other drawer. Probably I should create another ToolboxAttributes category called "Validation" attributes or something similar. It will affect every drawer/attribute based on validation (NotNull, Clamp, SceneObjectOnly, etc.).
- you are able to subscribe to ReorderableList callbacks using the `ReorderableListExposedAttribute`.
```
[ReorderableListExposed(OverrideNewElementMethodName = nameof(GetValue))]
public int[] list;

private int GetValue()
{
	return list.Length + Random.Range(0, 4);
}
```
