### ISSUE TITLE
Can you add a MinMaxIntSlider?

### ISSUE THREAD

**Issue by zfh2773333333** [arimger/Unity-Editor-Toolbox#91]
Used for the Vector2Int variable.

**Comment by arimger** [comment]
Do you mean the same drawer as MinMaxSlider for the Vector2? I can do it in the next update.

**Comment by zfh2773333333** [comment]
Yes, MinMaxSlider currently only supports floats, not integers. Thank you very much.

**Comment by arimger** [comment]
Implemented in: https://github.com/arimger/Unity-Editor-Toolbox/pull/93.

@zfh2773333333 you can use the same attribute: `MinMaxSliderAttribute`, it will work for Vector2 and Vector2Int properties.
