### ISSUE TITLE
[Feature Request] Hierarchy Tree View

### ISSUE THREAD

**Issue by Yueby** [arimger/Unity-Editor-Toolbox#99]
Hi! I have a feature request, is it possible to add tree view lines in Hierarchy?
Like this ↓
https://assetstore.unity.com/packages/tools/utilities/qhierarchy-28577

**Comment by arimger** [comment]
Hi, thanks for the request. I will add it to my TODO list but with medium priority.

**Comment by Yueby** [comment]
> Hi, thanks for the request. I will add it to my TODO list but with medium priority.

Thank you~

**Comment by arimger** [comment]
Hello, this feature has already been merged (https://github.com/arimger/Unity-Editor-Toolbox/pull/114).
